#sudo: false
# travis-ci.org build & test configuration
language: python

matrix:
    include:
        - python: 3.6
          env: JUPYTER=true
        - python: 3.7
          env: JUPYTER=true
        - python: 3.7
          env: JUPYTER=false
        - python: 3.8
          env: JUPYTER=true
    allow_failures:

install:
  - pip install --upgrade pip
  - pip install -e '.[tests]'
  - if "$JUPYTER"; then
      pip install -e '.[jupyter]';
    fi
  - pip install codecov

script:
  - pytest --cov

after_success:
  - coverage combine
  - codecov

cache: apt

deploy:
  provider: pypi
  user: tai.sakuma
  distributions: sdist bdist_wheel --universal
  password:
    secure: VnLG0Cix35nPBLIa3/X5/A5kK+n4s7bzBJ+m/sm/j4G62ihh8YB+2mUt9PLlO75vIWslFYk4cBH1IH/w3GHhlXj1Dnc6tY7n/3km+Co1fQuTWSodomPoUU/XdBcqTrxpuVy81Cmw20mxFaOq/9vrTmSUaGJWxnRoAZLMf/SF3/Lsiiy384MYyWGd2FRMV7hGcps27ZQDhbqJrcJklIh8yE+UN5lQuUCw6+lizV3Xk0sBF+hMxno4wI+cT4TXVm5BqojdGzJXCRslMfxLC/ANi8sJ1iSJJl6mYMonvYPb3d8i/Cz3aKqJcbRRPK0q25vqWU9TDOCrkN6GW959PUHe8kjeEARCw7kHMBUNydn3xg5AVJTSjcPBhPC0Y4/pLTddIwk8esSvz8y2pAbihHR2MqO7OydTL2oEWB74iGv2IGpuR0VHC5HZhFS9QuY9XoS0jmGCk4IL68YhD8SgTiZ6eRLWlHBeU4vWos4cqjYYxoX0DAkdeCG/f5vgPBJLwMikjtwfZAlqQiQTVgrSQ8Kr+l047zDd+m7gTONjCm+nsPYXUJFQQ8+Rd9/BnfrXdNGJXmUTg1HPRUZITWqi2JmjMjQ456goErHxbW+mQ6VrRxRJ9nxy8Ax1OeVS5h+BBB2QxSTFFJtpXjisea3MkeV3MOPluh/RcoOgHyMY0Ho4h54=
  on:
    tags: true
    python: 3.7
    condition: $JUPYTER == true && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
