#sudo: false
# travis-ci.org build & test configuration
language: python

matrix:
    include:
        - python: 2.7
          env: JUPYTER=true
        - python: 3.6
          env: JUPYTER=true
        - python: 3.7
          env: JUPYTER=true
        - python: 3.7
          env: JUPYTER=false
        - python: 3.8
          env: JUPYTER=true
    allow_failures:
        - python: 2.7
          env: JUPYTER=true

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${TRAVIS_PYTHON_VERSION%-*}
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  - if "$JUPYTER"; then
      pip install -r requirements/jupyter.txt;
      if [ ${TRAVIS_PYTHON_VERSION%-*} == '2.7' ]; then
        pip install -r requirements/jupyter-extra-py27.txt;
      fi;
    fi
  - python setup.py -q install
  - pip install -r requirements/test.txt

script:
  - pytest --cov

after_success:
  - coverage combine
  - codecov

cache: apt

deploy:
  provider: pypi
  user: tai.sakuma
  distributions: sdist bdist_wheel --universal
  password:
    secure: VnLG0Cix35nPBLIa3/X5/A5kK+n4s7bzBJ+m/sm/j4G62ihh8YB+2mUt9PLlO75vIWslFYk4cBH1IH/w3GHhlXj1Dnc6tY7n/3km+Co1fQuTWSodomPoUU/XdBcqTrxpuVy81Cmw20mxFaOq/9vrTmSUaGJWxnRoAZLMf/SF3/Lsiiy384MYyWGd2FRMV7hGcps27ZQDhbqJrcJklIh8yE+UN5lQuUCw6+lizV3Xk0sBF+hMxno4wI+cT4TXVm5BqojdGzJXCRslMfxLC/ANi8sJ1iSJJl6mYMonvYPb3d8i/Cz3aKqJcbRRPK0q25vqWU9TDOCrkN6GW959PUHe8kjeEARCw7kHMBUNydn3xg5AVJTSjcPBhPC0Y4/pLTddIwk8esSvz8y2pAbihHR2MqO7OydTL2oEWB74iGv2IGpuR0VHC5HZhFS9QuY9XoS0jmGCk4IL68YhD8SgTiZ6eRLWlHBeU4vWos4cqjYYxoX0DAkdeCG/f5vgPBJLwMikjtwfZAlqQiQTVgrSQ8Kr+l047zDd+m7gTONjCm+nsPYXUJFQQ8+Rd9/BnfrXdNGJXmUTg1HPRUZITWqi2JmjMjQ456goErHxbW+mQ6VrRxRJ9nxy8Ax1OeVS5h+BBB2QxSTFFJtpXjisea3MkeV3MOPluh/RcoOgHyMY0Ho4h54=
  on:
    tags: true
    python: 3.7
    condition: $JUPYTER == true && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
